### ISSUE TITLE
A few ideas for blue/green deploys

### ISSUE THREAD

**Issue by pholleran** [trip-viewer/trip-viewer#28]
**Assumptions:** (please correct me if I am wrong)

* we will use Azure AppService Deployment Slots
* we will have scripts to perform swap and rollback

**Ideas:**

* We could just perform the swap in the portal (easy)
* Scripts could be triggered via a chat command in Teams (moderate)
* Scripts could be triggered from within the GitHub Pull Request using something like a slash command `/swap` or `/rollback`  (moderate)
* We could leverage GitHub's [Deployments API](https://developer.github.com/v3/repos/deployments/) to log deployment events to the Pull Request -- [example](https://itnext.io/what-is-the-github-deployments-api-638ce3088ed2) (over engineering for the task at hand)

**Examples for over-engineered GH-centric deployment:**

Here are example workflow files in a demo commonly used by my team. Sorry for the long scroll, the repo is private. Things to look at are:

* `if: startsWith(github.event.comment.body, '/approve')` uses [github-script](https://github.com/actions/github-script) to listen for comments. This can be a gate to trigger the next step.
* deployments using the Deployments API can include information in the `payload` - [api docs](https://developer.github.com/v3/repos/deployments/#parameters-1). This could be useful if a job/script to swap slots is initiated from a PR. In such a job we may want to validate that the deployment presently in the `staging` slot was created by the deployment of the current PR. We could do this by getting the containerID currently deployed to the staging AppService (assuming this can be obtained from the API) and comparing it to the containerID in the most recent deployment event logged to the PR. If they match, perform the swap. If not, we would return a message to the PR stating that this PR needs to be deployed to staging in order to swap it.
 
```yaml
on:
  issue_comment:
    types: [created]
name: React on issue comments
jobs:
  react-on-issue-comment-not-approved:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Deploy Octocat Generator on') && startsWith(github.event.comment.body, '/approve') && github.event.issue.user.login == github.event.comment.user.login
    steps:
      - name: Need approval from somebody else
        uses: actions/github-script@0.5.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 @' + context.actor + ', you cannot approve your own deployment, somebody else has to add an ```/approve``` comment.'
            })
  react-on-issue-comment-approved:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Deploy Octocat Generator on') && startsWith(github.event.comment.body, '/approve') && github.event.issue.user.login != github.event.comment.user.login
    steps:
      - name: Approval granted
        uses: actions/github-script@0.5.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 @' + context.actor + ', approval granted, creating deployment request ...'
            })
      - name: Kicking off deployment
        uses: actions/github-script@0.5.0
        env:
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
        with:
          github-token: ${{secrets.GPR_PAT}}
          script: |
            const { title, body } = process.env;
            let cloud = title.match(/^Deploy Octocat Generator on (.*)/)[1]
            let customer = body.match(/^Customer: (.*)/)[1]
            let customerNormalized = customer.replace(/[^a-zA-Z0-9_\-]*/g, '')
            let gprUrl='docker.pkg.github.com/'+context.repo.owner.toLowerCase()+'/'+context.repo.repo.toLowerCase()+'/octocat-generator-docker:'+customerNormalized
            github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref:  customerNormalized,
              task: 'deploy-to-' + cloud,
              auto_merge: false,
              required_contexts: [],
              environment: cloud + '-' + customerNormalized + '-' + context.issue.number,
              description: 'Production environment for ' + customer + ' on ' + cloud,
              payload:  { customer: customer, cloud: cloud, gprUrl: gprUrl, issue: context.issue.number, customerNormalized: customerNormalized },
              production_environment: false,
              transient_environment: false
            })
```

and the logic run by the deployment job

```yaml
name: Deploy to Azure
on: [deployment]

jobs:
  deploy-to-azure:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    env:
      issue_number: '${{github.event.deployment.payload.issue}}'
      cloud: '${{github.event.deployment.payload.cloud}}'
      gprUrl: '${{github.event.deployment.payload.gprUrl}}'
      customer: '${{github.event.deployment.payload.customer}}'
      deployment_id: '${{github.event.deployment.id}}'
      TF_VAR_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      TF_VAR_client_id: ${{ secrets.AZ_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.AZ_CLIENT_SECRET }}
      TF_VAR_tenant_id: ${{ secrets.AZ_TENANT_ID }}
      TF_VAR_github_pat: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_gpr_url: ${{github.event.deployment.payload.gprUrl}}
      TF_VAR_github_user: ${{ github.actor }}

    if:  startsWith(github.event.deployment.task, 'deploy-to-Azure')
    steps:
    - name: Announce deployment
      uses: actions/github-script@0.5.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { issue_number, cloud, gprUrl, customer, deployment_id } = process.env;
          let log_url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/` + process.env.GITHUB_RUN_ID
          github.repos.createDeploymentStatus({
            mediaType: {
              previews: ["flash-preview", "ant-man"]
            },
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: deployment_id,
            state: 'in_progress',
            description: 'Kicking off deployment on ' + cloud + ' for ' + customer  + ' now.',
            target_url: log_url,
            log_url: log_url
          })
          github.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ':rocket: Kicking off deployment on ' + cloud + ' for ' + customer + ' now. [View deployment live logs](' +  log_url + ').'
          })
    - name: 'Checkout'
      if: (false)
      uses: actions/checkout@master

    - REDACTED DEPLOYMENT LOGIC   

    - name: Update deploy success
      if: (success())
      uses: actions/github-script@0.5.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { issue_number, cloud, gprUrl, customer, deployment_id } = process.env;
          let log_url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/` + process.env.GITHUB_RUN_ID
          github.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: deployment_id,
            state: 'success',
            description: 'Deployed successfully to ' + cloud + ' for ' +  customer,
            environment_url: 'https://octocatgenerator.z6.web.core.windows.net/',
            target_url: log_url,
            log_url: log_url
          })
          github.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ':white_check_mark: Deployed successfully to ' + cloud + ' for ' +  customer + ': ' + 'https://octocatgenerator.z6.web.core.windows.net/'
          })
          github.issues.addLabels({
              issue_number: issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['deployed']
          })
    - name: Update deploy failure
      if: (failure())
      uses: actions/github-script@0.5.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { issue_number, cloud, gprUrl, customer, deployment_id } = process.env;
          let log_url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/` + process.env.GITHUB_RUN_ID
          github.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: deployment_id,
            state: 'failure',
            description: 'Deployment to ' + cloud + ' failed for ' +  customer + ' :cry:',
            target_url: log_url,
            log_url: log_url
          })
          github.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ':red_circle: Deployment to ' + cloud + ' failed for ' +  customer + ' :cry:. [View failed deployment logs](' + log_url + ').'
```
